precursor:
  precursor_mz:
    min: 200.0
    max: 1200.0
extract_and_fit_chroms:
  min_rel_height: 0.25
  min_abs_height: 10000.0
  fwhm:
    min: 0.05
    max: 0.5
  max_peaks: 3
  min_psnr: 5.0
  mz_ppm: 40.0
  rt_tol: null
consolidate_chrom_feats:
  mz_ppm: 40.0
  rt_tol: 0.1
extract_and_fit_ms2_spectra:
  min_rel_height: 0.05
  min_abs_height: 1000.0
  fwhm:
    min: 0.02
    max: 0.2
  peak_min_dist: 0.2
  pre_mz_ppm: 60.0
  mz_bin_min: 50.0
  mz_bin_size: 0.05
consolidate_dda_feats:
  mz_ppm: 100.0
  rt_tol: 0.1
  drop_if_no_ms2: false
